language: node_js
node_js:
  - "7"

cache:
  directories:
    - $HOME/node_modules

before_install: true

install:
- docker run --rm -it node npm install

before_script: true

script: true

after_script: true
