language: node_js
node_js:
  - "7"

cache:
  directories:
    - $HOME/node_modules

install:
- npm install

before_script: true

script:
  - node_modules/.bin/jshint src
  - node_modules/.bin/retire

after_script:
  - ls && git branch
