language: node_js
node_js:
  - "7"

cache:
  directories:
    - $HOME/node_modules

install:
- npm install

before_script: true

script:
  - node_modules/.bin/jshint src
  - node_modules/.bin/retire

after_script: 
  - "git branch | grep * | cut -d ' ' -f2"

deploy:
    provider: heroku
    api_key:
        secure: <api_key>
    app: testjs-ci-cd
