language: node_js
node_js:
  - "7"

cache:
  directories:
    - $HOME/node_modules

before_install:
   - apt-get update
   - apt-get install -y git

install:
- npm install

before_script: true

script:
  - node_modules/.bin/jshint src
  - node_modules/.bin/jshint retire

after_script:
  - ls && git branch
